### ISSUE TITLE
How can I determine the current mode?

### ISSUE THREAD

**Issue by jiz4oh** [kana/vim-gf-user#4]
Hi @kana, thank you for creating the plugin, I have a question when I write my own plugin.

I want to infer the file path by the `selected text` in `visual mode` and the `<cfile>` in `normal mode`, but how can I determine the current mode in the `gf-user-extension-function`?

I tried to get mode by `mode()`, but it always returns `n`.

**Comment by kana** [comment]
Thank you for the feedback.  It is not possible to get the current mode from `gf-user-extension-function` due to the current implementation of vim-gf-user.  I think the problem can be fixed.  I'll look into it later.

**Comment by jiz4oh** [comment]
thanks your quickly action
